<template>
  <main>
    <div>
      <ImageGridItem
        buttontext="button"
        buttonlink="acs"
        maintext="akn"
        maindesc="kjasd"
      ></ImageGridItem>
    </div>
  </main>
</template>
